### ISSUE TITLE
Possible bug mistakenly detecting errors?

### ISSUE THREAD

**Issue by WOOMYWOOMY** [Tom852/FallGuysNameFinder#5]
The program works great, except for some reason always stops after 10-11 name rerolls. I assume something is falsely triggering the "10 consecutive major errors" thing, as that is what the console states the reason for the engine stopping is. The only options I have on are "Auto confirm name," "Verbose console," and "Always on top," and I am using exclusively the Pool Matching and not the Pattern Matching. The program seems to be working perfectly fine, so I don't think the program is correctly identifying 10 major errors

I will say that it _could_ be an issue on my end, as maybe my nickname is clashing with the system? I only have Bouncy Bean, Rhino Tamer, and Rookie, and all three have produced this issue, so maybe it's just that.

I can share whatever console information if needed. I'm not super familiar with coding/tech stuff so please bear with me haha

**Comment by WOOMYWOOMY** [comment]
Here's the file:

Thank you!
[FallGuysNameFinder (2).zip](https://github.com/Tom852/FallGuysNameFinder/files/7446111/FallGuysNameFinder.2.zip)

**Comment by Tom852** [comment]
That's the wrong file. I need the one with the logs. It is this path:
`C:\Users\[Your User Name]\AppData\Roaming\FallGuysNameFinder`

It looks like that:
![g](https://user-images.githubusercontent.com/38071521/139527874-6f15be67-53a6-46f0-b3ac-92496382bf30.png)

**Comment by WOOMYWOOMY** [comment]
Oh, I see now! Here's the file from AppData/Roaming 😅

[FallGuysNameFinder.zip](https://github.com/Tom852/FallGuysNameFinder/files/7451872/FallGuysNameFinder.zip)

**Comment by Tom852** [comment]
Your resolution is not reported correctly, and thus the screenshot area is at the wrong place.
Can it be you have a windows scaling?

Try set it to 100%

![image](https://user-images.githubusercontent.com/38071521/139658348-75c19302-668e-49c3-9232-c0de5efa63ca.png)

**Comment by WOOMYWOOMY** [comment]
That fixed the issue! Thank you so much for your help! 😊
